### ISSUE TITLE
FR: IP whitelist settings field

### ISSUE THREAD

**Issue by jamesmacwhite** [sjelfull/craft3-restrict#10]
Currently the plugin works with an array of IP address/range values. Perhaps a future idea would be for the Restrict plugin to have a settings field that can store IP addresses.

My initial thoughts would be a multi line text field where each IP address/range would be separated on a new line. I feel there would need to be additional validation to make sure each line contains a valid IP address/range before being committed to a settings field.

**Comment by sjelfull** [comment]
This plugin has been abandoned. Use [Knock Knock](https://github.com/verbb/knock-knock) as an alternative.
