### ISSUE TITLE
Not recognizing IPs in restrict.php file

### ISSUE THREAD

**Issue by nathannerdymind** [sjelfull/craft3-restrict#11]
I just added the plugin to a Craft site running 3.4.22.1
I added the IPs as listed 
`'ipWhitelist' => [ '::1', '127.0.0.1', '00.000.000.000', '00.000.000.000', '00.000.000.000'],`

But none of the users can access the backend. We cleared the site cache but we are still getting blocked. 
Our file is in `/config/restrict.php`

Any suggestions?

**Comment by jl-digital** [comment]
Same problem here, any suggestions @sjelfull?

**Comment by sjelfull** [comment]
This plugin has been abandoned. Use [Knock Knock](https://github.com/verbb/knock-knock) as an alternative.
