### ISSUE TITLE
Does this work with Craft 3? 

### ISSUE THREAD

**Issue by baileydoestech** [sjelfull/craft3-restrict#2]
Tried porting this plugin with existing configuration from Craft 2 to Craft 3 - behavior seems to be the opposite of what is advertised i.e. site is only accessible if you are logged in to Craft through the CP

**Comment by sjelfull** [comment]
Thanks for reporting this. The plugin doesn't check if this is actually a CP request. Will have a fix out soon.

**Comment by baileydoestech** [comment]
Any update on when this might be released?

**Comment by sjelfull** [comment]
Pushed new release now.
