### ISSUE TITLE
FR: Support for wildcard/CIDR notation for whitelisting IP addresses

### ISSUE THREAD

**Issue by jamesmacwhite** [sjelfull/craft3-restrict#3]
In a Craft 2 project I use this plugin to whitelist the CP to a set of IP addresses within our organisation and a few individuals, these were a combination of single IP addresses as well as "ranges". I ended up hacking in support for ranges by basically making the plugin aware of the "*" character using regex so something like `192.168.*` would match all IP addresses beginning with `192.168`.

It would be nice if this could be possible in the Craft 3 plugin. Performance wise I'm not sure the regex approach is ideal for large amounts of IP addresses. It would probably be better to handle CIDR notation like 192.168.0.0/24 or similar, but this would require a fair bit of work hence the feature request!

**Comment by sjelfull** [comment]
Luckily there is already packages that handles this: https://packagist.org/packages/dxw/cidr

Would you mind submitting a PR?

**Comment by jamesmacwhite** [comment]
That's useful! I'll certainly look at helping implementing this. I am currently in the early stages of migrating the original site that uses the Craft 2 version, I'll look at submitting a PR!

**Comment by jamesmacwhite** [comment]
https://github.com/sjelfull/craft3-restrict/pull/4
