### ISSUE TITLE
Template option and potential race condition with other plugins

### ISSUE THREAD

**Issue by jamesmacwhite** [sjelfull/craft3-restrict#7]
@sjelfull It occurred to me I never followed up regarding your comment on https://github.com/sjelfull/craft3-restrict/issues/5#issuecomment-479453768. How rude of me, apologies.

So I looked into the issue a bit more, so the scenario can be in some cases when using the template option and pointing to a template that uses extends that may reference other plugins i.e. twig filters etc, you will get an error when Restrict tries to render the template, because it won't exist at that time.

In the plugins init function, if you change the existing check service call to:

```php
Event::on(
    Plugins::class,
    Plugins::EVENT_AFTER_LOAD_PLUGINS,
    function () {
        if (Craft::$app->getRequest()->isCpRequest) {
	    $this->restrictService->check();
        }
    }
);
```

This fixes that problem and allows the rendering of the template to continue, as it's now being loaded after everything else. However, I think some further thought is needed around:

https://github.com/sjelfull/craft3-restrict/blob/master/src/services/RestrictService.php#L88

Fixing the potential race condition shows that the head and footer section of the specified template do not get parsed, instead we see the placeholders: https://github.com/yiisoft/yii2-framework/blob/master/web/View.php `<![CDATA[YII-BLOCK-HEAD]]>` and `<![CDATA[YII-BLOCK-BODY-END]]>`. The makes sense because it's simply being echo'd without any Yii awareness in this regard.

Wondered what your thoughts are?

Thanks!

**Comment by sjelfull** [comment]
Thanks for commenting James!

This plugin has been abandoned. Use [Knock Knock](https://github.com/verbb/knock-knock) as an alternative.
